### ISSUE TITLE
Timeouts on PS5

### ISSUE THREAD

**Issue by misohu** [charmed-kubernetes/github-runner-operator#22]
I tried to run runners from PS5. I ended up with following problem: Charm creates the instance (I can see it with `openstack server list`), but it gets stuck in maintanance status. 

```
Model                        Controller    Cloud/Region           Version  SLA          Timestamp
prod-kubeflow-github-runner  prodstack-is  prodstack5/prodstack5  2.9.32   unsupported  11:12:47Z

App            Version  Status       Scale  Charm          Store       Rev  OS      Notes
github-runner           maintenance      1  github-runner  jujucharms    1  ubuntu  

Unit              Workload     Agent  Machine  Public address  Ports  Message
github-runner/3*  maintenance  idle   3        10.134.226.161         Checking for runner updates

Machine  State    DNS             Inst id                               Series  AZ                   Message
3        started  10.134.226.161  f32360f4-00b7-4484-add1-6e1290e33851  focal   availability-zone-3  ACTIVE
```

Looking at debug log I see timeouts:
```
unit-github-runner-3: 11:05:00 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-github-runner-3: 11:07:44 ERROR unit.github-runner/3.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 270, in <module>
    main(GithubRunnerOperator)
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/ops/main.py", line 426, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/ops/framework.py", line 276, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/ops/framework.py", line 736, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/ops/framework.py", line 783, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 123, in _on_update_runner_bin
    runner_bin_url = runner_manager.get_latest_runner_bin_url()
  File "/var/lib/juju/agents/unit-github-runner-3/charm/src/runner.py", line 113, in get_latest_runner_bin_url
    runner_bins = self.api.actions.list_runner_applications_for_repo(
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/ghapi/core.py", line 63, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/ghapi/core.py", line 108, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=self.debug, return_headers=True,
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/fastcore/net.py", line 212, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/fastcore/net.py", line 111, in urlread
    with urlopen(url, data=data, headers=headers, timeout=timeout, **kwargs) as u: res,hdrs = u.read(),u.headers
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/fastcore/net.py", line 105, in urlopen
    return _opener.open(urlwrap(url, data=data, headers=headers), timeout=timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
machine-3: 11:07:44 INFO juju.util.exec run result: exit status 1
```

I deployed The runner with my PAT and set the path to point to one of our repos `canonical/knative-operators`. I Also set the ACLs properly (check [here](https://bazaar.launchpad.net/~prod-internal-proxy/canonical-is-internal-proxy-configs/trunk/view/head:/squid.conf#L4658)). I tried to ssh to the instance and access the github and EPs for the runners without problem. I also tried to setup proxy manually in the instance editing the `/etc/environment` 

```
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

HTTP_PROXY=http://squid.internal:3128
HTTPS_PROXY=http://squid.internal:3128
http_proxy=http://squid.internal:3128
https_proxy=http://squid.internal:3128
JUJU_CHARM_HTTP_PROXY=http://squid.internal:3128
JUJU_CHARM_HTTPS_PROXY=http://squid.internal:3128
JUJU_CHARM_NO_PROXY="localhost,127.0.0.1,127.0.0.0/8,10.0.0.0/8,10.130.0.0/16,192.168.0.0/16,10.152.0.0/16,.jujucharms.com,juju-f1c044-prod-kubeflow-github-runner-3"
NO_PROXY="localhost,127.0.0.1,127.0.0.0/8,10.0.0.0/8,10.130.0.0/16,192.168.0.0/16,10.152.0.0/16,.jujucharms.com,juju-f1c044-prod-kubeflow-github-runner-3" 
no_proxy="localhost,127.0.0.1,127.0.0.0/8,10.0.0.0/8,10.130.0.0/16,192.168.0.0/16,10.152.0.0/16,.jujucharms.com,juju-f1c044-prod-kubeflow-github-runner-3"
```

I also manually set these:
```
JUJU_CHARM_HTTPS_PROXY=http://squid.internal:3128
JUJU_CHARM_HTTP_PROXY=http://squid.internal:3128
JUJU_CHARM_NO_PROXY=localhost,127.0.0.1,127.0.0.0/8,10.0.0.0/8,10.130.0.0/16,192.168.0.0/16,10.152.0.0/16,.jujucharms.com,juju-f1c044-prod-kubeflow-github-runner-3
```

Still no success. Can you please help me.

**Comment by mthaddon** [comment]
Note that the locations self-hosted runners connect to is documented here: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#communication-between-self-hosted-runners-and-github

**Comment by mthaddon** [comment]
I believe this may simply be that the proxy in question wasn't configured as expected, but will update again here once confirmed.

**Comment by mthaddon** [comment]
This appears to be a token configuration issue. I just tried creating a "classic" token and gave it `Full control of private repositories`, and was then ran the following from the same environment this issue was reported:
```
root@juju-f1c044-prod-kubeflow-github-runner-3:/var/lib/juju/agents/unit-github-runner-3/charm# python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append(".")
>>> sys.path.append("venv")
>>> from src.runner import RunnerManager
# First of all with a token I created:
#  - Cannot connect to 'canonical/knative-operators' but can connect to 'canonical/nginx-ingress-integrator-operator'
>>> runner = RunnerManager('canonical/knative-operators', 'REDACTED', 'github-runner', 5)
>>> runner.get_latest_runner_bin_url()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lib/juju/agents/unit-github-runner-3/charm/src/runner.py", line 113, in get_latest_runner_bin_url
    runner_bins = self.api.actions.list_runner_applications_for_repo(
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/ghapi/core.py", line 63, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/ghapi/core.py", line 108, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=self.debug, return_headers=True,
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/fastcore/net.py", line 212, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/var/lib/juju/agents/unit-github-runner-3/charm/venv/fastcore/net.py", line 113, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp) from None
fastcore.basics.HTTP403ForbiddenError: HTTP Error 403: Forbidden
>>> runner = RunnerManager('canonical/nginx-ingress-integrator-operator', 'REDACTED', 'github-runner', 5)
>>> runner.get_latest_runner_bin_url()
'https://github.com/actions/runner/releases/download/v2.298.2/actions-runner-linux-x64-2.298.2.tar.gz'
>>> 
```
I think the difference here is that this token is created for me, and I'm not an admin on the "canonical/knative-operators" repo, but I am on "canonical/nginx-ingress-integrator-operator". Can you confirm if you're an admin on "canonical/knative-operators"?

The fact that I'm able to connect for one repo means this isn't an access issue (any more).

**Comment by mthaddon** [comment]
Additionally, the errors in your original paste show connection timed out. Can you confirm with the Juju team if setting those env variables in `/etc/environment` is recognised by Juju, or if you need to use the relevant `juju model-config` options instead (if so I think you may need to also create a new unit after having set these, not sure if it'll retroactively apply to existing units).

**Comment by misohu** [comment]
You need to specify juju proxy options with 
```
juju model-config juju-http-proxy=http://squid.internal:3128
juju model-config juju-https-proxy=http://squid.internal:3128
juju model-config juju-no-proxy=localhost,127.0.0.1,127.0.0.0/8,10.0.0.0/8,10.130.0.0/16,192.168.0.0/16,10.152.0.0/16,.jujucharms.com
```

Don't set the `http-proxy` and `https-proxy` as you can only have one of those setup.

**Comment by ca-scribner** [comment]
@misohu can you clarify your comment "Don't set the http-proxy and https-proxy as you can only have one of those setup."?  Do you mean that  `juju-http-proxy` and `juju-https-proxy` should not be set at the same time, or that `juju-http-proxy/juju-https-proxy` should not be set at the same time as `http-proxy/https-proxy`?  I see in the code block you set both `juju-http-proxy` and `juju-https-proxy` and got confused.

**Comment by mthaddon** [comment]
@ca-scribner he means that `juju-http-proxy/juju-https-proxy` should not be set at the same time as `http-proxy/https-proxy`. I think juju even warns you that it's not possible to have both set at the same time.
